GET http://localhost:3000/u/sadge HTTP/1.1


###
GET http://localhost:3000/index.html HTTP/1.1

###
GET http://localhost:3000/views/index.html HTTP/1.1

### 
// posting url
POST http://localhost:3000/submit 
Content-Type: application/json

{
    "endUrl": "www.foobar.foo/sadgebar",
    "shortUrl": "sadge"
}

###
// register user

POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username": "frogee",
    "email": "pepe@froge.com",
    "password": "asdfqwqe"
}

###
// login user

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "pepe@froge.com",
    "password": "asdfqwqe"
}
###
// login user with wrong pass

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "pepe@froge.com",
    "password": "asdfqwqee"
}